# Docker-specific configuration

# Server configuration
server:
  port: 8080
  tomcat:
    max-threads: 200
    max-connections: 10000

# Logging configuration
logging:
  level:
    com.example.springbootwebsocket: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# WebSocket configuration
# In production, you should restrict allowed origins
# websocket:
#   allowed-origins: https://your-domain.com
